# Deployment
## Docs: https://hexo.io/docs/deployment.html
url: http://www.sallyjin.com
theme: next
title: 金老师的知识花园
author: sally.jin
language: zh-Hans
deploy:
  type: git
  repo: git@github.com:terryzhu/terryzhu.github.io.git
  branch: master
  plugins:
    - hexo-generator-cname
